name: load

on:
  push

jobs:
  load:
    runs-on: ubuntu-latest
    defaults:
        run:
          working-directory: pub-trends-cli
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '3.1.x'
      - run: dotnet build PubTrends.csproj
      - run: dotnet ${{GITHUB_WORKSPACE}}/bin/Debug/netcoreapp3.1/PubTrends.dll ${{GITHUB_WORKSPACE}}/../packages.txt ${{GITHUB_WORKSPACE}}/../docs/pub.db