name: load

on:
  push

jobs:
  load:
    runs-on: ubuntu-latest
    defaults:
        run:
          working-directory: pub-trends-cli
    env:
      PACKAGES: $GITHUB_WORKSPACE/../packages.txt
      DATABASE: $GITHUB_WORKSPACE/../docs/pub.db
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '3.1.x'
      - run: dotnet run PubTrends.csproj